---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: init | ansible | create group
      group:
        name: ansible
        state: present

    - name: init | ansible | create user
      user:
        name: ansible
        group: ansible
        groups: wheel
        state: present
        comment: "Ansible"
        system: yes
        shell: /usr/bin/nologin

    - name: init | ansible | add sudoers file
      copy:
        src: sudoers_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

    - name: init | openssh | [Arch] installation
      package:
        name: openssh
        state: latest
      when: ansible_distribution == "Archlinux"

    - name: init | openssh | [Debian] installation
      package:
        name: openssh-server
        state: latest
      when: ansible_distribution == "Debian"

    - name: init | openssh | [Arch] start daemon
      systemd:
        name: sshd
        state: started
        enabled: yes
      when: ansible_distribution == "Archlinux"

    - name: init | openssh | [Debian] start daemon
      systemd:
        name: ssh
        state: started
        enabled: yes
      when: ansible_distribution == "Debian"

    - name: init | ssh | create dir
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        mode: 0600

    - name: init | ssh | key-gen
      openssh_keypair:
        path: /home/ansible/.ssh/ansible-ed25519
        type: ed25519
        state: present
        owner: ansible
        comment: "Ansible"
...
